openapi: 0.0.0
info:
  title: Flask API
  description: This is Flask API that takes a sentence as input and returns a random 500 dimensional array.
  version: 0.0.0
servers:
  - url: http://localhost:8080
    description: This value defines base URL of API.
paths:
  /:
    get:
      summary: Returns the default response from the API.
      description: Defaul route for API.
      responses:
        '200':    # status code
          description: The default response.
          content:
            text/plain:
              "Hello, This is Flask API that takes a sentence as input and returns a random 500 dimensional array of floats."
  /health:
    get:
      summary: Used to check the API is responsive.
      description: Checks Health of API.
      responses:
        '200':    # status code
          description: The default response.
          content:
            text/plain:
              "OK"
  /getEmbedding:
    post:
      summary: Take sentence as a input and returns 500 dim array.
      description: Take sentence as a input and returns 500 dim array.
      requestBody:
        text/plain:
              sentence:
                type: string
      responses:
        '200':    # status code
          description: The default response.
          content:
            text/plain:
              message:
                type: string  
              data:
                type: array          